server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: Users
          uri: http://localhost:7071
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: AUTH
          uri: http://localhost:7071
          predicates:
            - Path=/auth/**
            #- Path=/admin/subscription

        - id: Store-Service
          uri: http://localhost:7072
          predicates:
            - Path=/api/store/**
          filters:
            - AuthenticationFilter

        - id: Order-Service
          uri: http://localhost:7075
          predicates:
            - Path=/api/orders/**
            - Path=/api/products/**
            - Path=/api/category/**
          filters:
            - AuthenticationFilter

        - id: Inventory-Service
          uri: http://localhost:7074
          predicates:
            - Path=/api/inventory/**
          filters:
            - AuthenticationFilter

        - id: Branch-Service
          uri: http://localhost:7073
          predicates:
            - Path=/api/branch/**
          filters:
            - AuthenticationFilter

        - id: Payment-Service
          uri: http://localhost:7076
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

