spring:
  application:
    name: Inventory-Service
  datasource:
    url: jdbc:mysql://localhost:3307/commercehub
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7074

user:
  service:
    url: http://localhost:7071

store:
  service:
    url: http://localhost:7072

branch:
  service:
    url: http://localhost:7073

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: health

  endpoint:
    health:
      show-details: always

#Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

      branchService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

      storeService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
