apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: commercehub
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30800
  selector:
    app: phpmyadmin