spring:
  application:
    name: Store-Service
  datasource:
    url: jdbc:mysql://localhost:3307/commercehub
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: store-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port: 7072

auth:
  service:
    url: http://localhost:7071/auth/

payment:
  service:
    url: http://localhost:7076/api/payment/

subscription:
  service:
    url: http://localhost:7071/admin/subscription

user:
  service:
    url: http://localhost:7071/api/users/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# Checking the health of the service
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: health

  endpoint:
    health:
      show-details: always

#Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

      paymentService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

      subscriptionService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
